### ISSUE TITLE
Course is published in packtpub

### ISSUE THREAD

**Issue by devopsdymyr** [PacktPublishing/Mastering-Elasticsearch-7.0#7]
Hi ,
I am planning to learn ELK for monitoring my aplication which is hosated in kubernetes.
Can you please add some details about EFK setup in Kubernetes using helm or any type.

Looking for your course link to start

**Comment by wtwong316** [comment]
Hi devopsdymyr,

Thank you for your suggestion.
However, Kubernetes is not in the scope of this book.  I do not have a plan to add it.
By the way, there are two web articles FYI.

(1)Get Kubernetes Logs with EFK Stack in 5 Minutes
https://akomljen.com/get-kubernetes-logs-with-efk-stack-in-5-minutes/

(2)How To Set Up an Elasticsearch, Fluentd and Kibana (EFK) Logging Stack on Kubernetesttps://www.digitalocean.com/community/tutorials/how-to-set-up-an-elasticsearch-fluentd-and-kibana-efk-logging-stack-on-kubernetes

**Comment by devopsdymyr** [comment]
Thanks for your response,

I have tried above articles but they are not mentioned filebeat for collect
logs, elastic login by authentication,
If you have any references send to me

Let me know when you're course going to launch

Regards
Kathir

**Comment by wtwong316** [comment]
This article seems quite complete for what you want.
Visualising services on Kubernetes with ELK... on Kubernetes
https://nick.sarbicki.com/blog/visualising-services-kubernetes-elk-kubernetes/

**Comment by devopsdymyr** [comment]
Thanks a lot,
Ping me once your course is ready

Regards,
Kathir
